/**
 * Mock Anthropic Client for Testing
 *
 * Simulates Anthropic API calls without making real requests.
 * Enable by setting: SIMULATE_ANTHROPIC=true in .env.local
 */

import Anthropic from '@anthropic-ai/sdk';

// Simulated generation patterns based on prompt type
const SIMULATED_RESPONSES: Record<string, string> = {
  bolt_generator: `<file path="package.json">
{
  "name": "generated-app",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start"
  },
  "dependencies": {
    "next": "14.2.5",
    "react": "18.3.1",
    "react-dom": "18.3.1"
  }
}
</file>

<file path="app/page.tsx">
export default function Home() {
  return (
    <div className="min-h-screen bg-zinc-950 text-white p-8">
      <h1 className="text-4xl font-bold mb-4">Generated App</h1>
      <p className="text-zinc-400">This app was generated by AutoForge (simulated mode)</p>
    </div>
  );
}
</file>

<file path="app/layout.tsx">
import './globals.css'

export const metadata = {
  title: 'Generated App',
  description: 'Built with AutoForge',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
</file>

<file path="app/globals.css">
@tailwind base;
@tailwind components;
@tailwind utilities;

body {
  margin: 0;
  padding: 0;
}
</file>

<file path="tailwind.config.js">
module.exports = {
  content: [
    './app/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {},
  },
  plugins: [],
}
</file>

<file path=".gitignore">
node_modules
.next
.env.local
</file>`,

  classifier: JSON.stringify({
    appType: 'web-app',
    complexity: 'simple',
    features: ['dashboard', 'forms'],
    confidence: 0.95,
  }),

  clarification: JSON.stringify({
    needsClarification: false,
    questions: [],
    suggestedDefaults: {
      theme: 'dark',
      framework: 'nextjs',
    },
  }),

  agent_review: JSON.stringify({
    issues: [],
    suggestions: [],
    passed: true,
    score: 0.95,
  }),

  support_response: "Thank you for contacting AutoForge support. I understand you're experiencing an issue. Let me help you resolve this. Could you provide more details about what you're seeing?",

  recommendation: JSON.stringify([
    {
      title: 'Add Authentication',
      description: 'Secure your app with user authentication',
      priority: 'high',
    },
    {
      title: 'Add Database',
      description: 'Store data persistently with Supabase',
      priority: 'medium',
    },
  ]),
};

class MockAnthropicStream {
  private response: string;
  private index: number = 0;
  private chunkSize: number = 50;

  constructor(response: string) {
    this.response = response;
  }

  async *[Symbol.asyncIterator]() {
    // Simulate streaming by chunking the response
    while (this.index < this.response.length) {
      const chunk = this.response.slice(this.index, this.index + this.chunkSize);
      this.index += this.chunkSize;

      yield {
        type: 'content_block_delta',
        delta: {
          type: 'text_delta',
          text: chunk,
        },
      };

      // Simulate network delay
      await new Promise(resolve => setTimeout(resolve, 50));
    }

    // Send final message
    yield {
      type: 'message_stop',
      message: {
        stop_reason: 'end_turn',
        usage: {
          input_tokens: 100,
          output_tokens: this.response.length / 4, // Rough estimate
        },
      },
    };
  }

  async finalMessage() {
    return {
      id: `sim_${Date.now()}`,
      type: 'message',
      role: 'assistant',
      content: [{ type: 'text', text: this.response }],
      model: 'claude-3-5-sonnet-20241022',
      stop_reason: 'end_turn',
      usage: {
        input_tokens: 100,
        output_tokens: this.response.length / 4,
      },
    };
  }
}

class MockAnthropicMessages {
  async create(params: any): Promise<any> {
    console.log('🎭 [SIMULATED] Anthropic API call intercepted');

    // Determine response type based on system prompt or user message
    let responseType = 'bolt_generator';
    const systemPrompt = params.system || '';
    const userMessage = params.messages?.[0]?.content || '';

    if (systemPrompt.includes('classify') || userMessage.includes('classify')) {
      responseType = 'classifier';
    } else if (systemPrompt.includes('clarification') || userMessage.includes('clarification')) {
      responseType = 'clarification';
    } else if (systemPrompt.includes('review') || systemPrompt.includes('agent')) {
      responseType = 'agent_review';
    } else if (systemPrompt.includes('support')) {
      responseType = 'support_response';
    } else if (systemPrompt.includes('recommend')) {
      responseType = 'recommendation';
    }

    const response = SIMULATED_RESPONSES[responseType] || SIMULATED_RESPONSES.bolt_generator;

    // Simulate processing delay
    await new Promise(resolve => setTimeout(resolve, 1000));

    return {
      id: `sim_msg_${Date.now()}`,
      type: 'message',
      role: 'assistant',
      content: [{ type: 'text', text: response }],
      model: params.model || 'claude-3-5-sonnet-20241022',
      stop_reason: 'end_turn',
      usage: {
        input_tokens: 100,
        output_tokens: response.length / 4,
      },
    };
  }

  stream(params: any): MockAnthropicStream {
    console.log('🎭 [SIMULATED] Anthropic streaming API call intercepted');

    // Determine response type
    let responseType = 'bolt_generator';
    const systemPrompt = params.system || '';

    if (systemPrompt.includes('classify')) {
      responseType = 'classifier';
    } else if (systemPrompt.includes('clarification')) {
      responseType = 'clarification';
    } else if (systemPrompt.includes('review') || systemPrompt.includes('agent')) {
      responseType = 'agent_review';
    }

    const response = SIMULATED_RESPONSES[responseType] || SIMULATED_RESPONSES.bolt_generator;
    return new MockAnthropicStream(response);
  }
}

class MockAnthropic {
  messages: MockAnthropicMessages;

  constructor(config?: any) {
    console.log('🎭 [SIMULATION MODE] Using Mock Anthropic Client');
    this.messages = new MockAnthropicMessages();
  }
}

/**
 * Get Anthropic client - real or simulated based on environment
 */
export function getAnthropicClient(apiKey?: string): Anthropic {
  const shouldSimulate = process.env.SIMULATE_ANTHROPIC === 'true';

  if (shouldSimulate) {
    console.log('🎭 Anthropic simulation mode enabled');
    return new MockAnthropic() as unknown as Anthropic;
  }

  // Use real client
  return new Anthropic({
    apiKey: apiKey || process.env.ANTHROPIC_API_KEY,
  });
}

/**
 * Check if we're in simulation mode
 */
export function isSimulationMode(): boolean {
  return process.env.SIMULATE_ANTHROPIC === 'true';
}
