'use client';

import { useState } from 'react';
import { DollarSign, ExternalLink, AlertCircle, Building2 } from 'lucide-react';

export default function MonetizationPage() {
  const [isConnected, setIsConnected] = useState(false);

  return (
    <div className="space-y-8">
      <div>
        <h2 className="text-xl font-bold mb-1">Monetization Settings</h2>
        <p className="text-sm text-gray-400">Configure how you receive payments from your generated apps</p>
      </div>

      {/* Stripe Connect Card */}
      <div className="p-6 bg-[#0A0A0B] border border-white/10 rounded-xl">
        <div className="flex items-start justify-between mb-6">
          <div className="flex gap-4">
            <div className="w-12 h-12 bg-[#635BFF] rounded-lg flex items-center justify-center">
              <DollarSign className="w-7 h-7 text-white" />
            </div>
            <div>
              <h3 className="font-bold text-lg">Stripe Connect</h3>
              <p className="text-sm text-gray-400">Receive payouts directly to your bank account</p>
            </div>
          </div>
          <div className={`px-3 py-1 rounded-full text-xs font-medium border ${
            isConnected 
              ? 'bg-green-500/10 text-green-400 border-green-500/20' 
              : 'bg-yellow-500/10 text-yellow-400 border-yellow-500/20'
          }`}>
            {isConnected ? 'Connected' : 'Not Connected'}
          </div>
        </div>

        <p className="text-sm text-gray-300 mb-6 leading-relaxed">
          AutoForge integrates with Stripe Connect to automatically handle billing for your SaaS applications. 
          Once connected, any revenue generated by your AI apps will be automatically routed to your connected bank account.
        </p>

        {isConnected ? (
          <div className="flex gap-3">
            <button className="px-4 py-2 bg-[#2A2A2C] border border-white/10 rounded-lg text-sm font-medium hover:bg-white/5 transition-colors">
              View Payout Dashboard
            </button>
            <button className="px-4 py-2 text-red-400 text-sm font-medium hover:underline">
              Disconnect
            </button>
          </div>
        ) : (
          <button 
            onClick={() => setIsConnected(true)} // Simulate connection
            className="flex items-center gap-2 px-4 py-2 bg-[#635BFF] text-white rounded-lg font-medium hover:bg-[#5349E8] transition-colors"
          >
            Connect with Stripe <ExternalLink className="w-4 h-4" />
          </button>
        )}
      </div>

      {/* Default Pricing Model */}
      <div className="space-y-4">
        <h3 className="font-medium">Default App Pricing</h3>
        <p className="text-sm text-gray-400">Set the default pricing model for new generated apps (can be overridden per project)</p>
        
        <div className="grid md:grid-cols-2 gap-4">
          <div className="p-4 bg-[#0A0A0B] border border-violet-500/50 rounded-lg relative">
            <div className="absolute top-4 right-4 text-violet-500">
              <CheckCircle2Icon className="w-5 h-5" />
            </div>
            <Building2 className="w-6 h-6 text-gray-400 mb-3" />
            <h4 className="font-bold mb-1">Subscription (SaaS)</h4>
            <p className="text-xs text-gray-500">Monthly recurring revenue with tiered plans.</p>
          </div>

          <div className="p-4 bg-[#0A0A0B] border border-white/10 rounded-lg opacity-50 cursor-not-allowed">
            <DollarSign className="w-6 h-6 text-gray-400 mb-3" />
            <h4 className="font-bold mb-1">One-time Payment</h4>
            <p className="text-xs text-gray-500">Coming soon.</p>
          </div>
        </div>
      </div>
    </div>
  );
}

function CheckCircle2Icon({ className }: { className?: string }) {
  return (
    <svg 
      className={className} 
      xmlns="http://www.w3.org/2000/svg" 
      width="24" height="24" 
      viewBox="0 0 24 24" 
      fill="none" 
      stroke="currentColor" 
      strokeWidth="2" 
      strokeLinecap="round" 
      strokeLinejoin="round"
    >
      <circle cx="12" cy="12" r="10" />
      <path d="m9 12 2 2 4-4" />
    </svg>
  );
}